name: changelog

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:


jobs:

  changelog:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3

      - name: read
        run: echo changelog = ${{steps.build_changelog.outputs.changelog}}
