name: changelog

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:


jobs:

  changelog:

    runs-on: ubuntu-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: remove contents
        run: |
         cp /dev/null test.txt
         echo 'testing-environment\n' >> test.txt
         echo 'Pull requests for this build\n${{ github.event.pull_request.title }}' >> test.txt
        
      #- name: Add contents
        #run: echo "testing-environment" >> test.txt

      #- name : Print Title of PR
        #run: echo The Title of your PR is ${{ github.event.pull_request.title }} >> test.txt
        
      - name: add changes
        uses: stefanzweifel/git-auto-commit-action@v4
