name: changelog

on:
  workflow_dispatch:
  push:
   branches:
   - main
  pull_request:
   types:
      - "synchronize"
  pull_request_review:
   types:
      - "submitted"
  
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:

  changelog:

    runs-on: ubuntu-latest
    environment: prod
    
    #permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      #contents: write

    steps:
      - name: Checkout the repositoryy
        uses: actions/checkout@v3
        
      - name: sleep
        run: sleep 100
