name: changelog

on:
  workflow_dispatch:
  push:
   branches:
   - main
  pull_request:
  
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:

  changelog:

    runs-on: ubuntu-latest
    environment: prod
    
    #permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      #contents: write

    steps:
      - name: Checkout the repositoryy
        uses: actions/checkout@v3
        
      - name: sleep
        run: sleep 3000
