name: changelog

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:

jobs:

  changelog:

    runs-on: ubuntu-latest
    
    #permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      #contents: write

    steps:
      - name: Checkout the repositoryy
        uses: actions/checkout@v3
        
      #- name: echo title
        #run: echo ${{ github.event.pull_request.title }}
        
      #- name: echo message
        #run: echo ${{ github.event.commits.message }}
        
      - name: pr
        uses: actions-ecosystem/action-get-merged-pull-request@v1
        id: get-merged-pull-request
        with:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: output
        run: echo ${{ steps.get-merged-pull-request.outputs.title }}
          
      #- name: remove contents
        #run: |
         #cp /dev/null test.txt
         #cat <<EOR >> test.txt
         #Test Release binary
         
         #Pull requests created for this build
         #${{ github.event.pull_request.title }}
         #EOR
         
      #- name: Setup upterm session 
        #uses: lhotari/action-upterm@v1
        
      #- name: Add contents
        #run: echo "testing-environment" >> test.doc

      #- name : Print Title of PR
        #run: echo The Title of your PR is ${{ github.event.pull_request.title }} >> test.txt
        
      #- name: add changes
        #uses: stefanzweifel/git-auto-commit-action@v4
        #with:
          #file_pattern: '*.txt'
