name: changelog

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:


jobs:

  changelog:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name : Print Title of PR
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}
