name: changelog

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:


jobs:

  changelog:

    runs-on: ubuntu-latest
    
    #permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      #contents: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: Add contents
        run: echo "test-2" >> test.txt
        
      - name: add changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}

      - name : Print Title of PR
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}
        
      - name : Print messgae of PR
        run: echo The Title of your PR is ${{ github.event.commits.message }}
