name: Enforce Merge Method

on:
  pull_request:
    types:
      - closed

jobs:
  check_merge_method:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check merge method
        run: |
          BRANCH=${{ github.event.pull_request.base.ref }}
          MERGE_METHOD=${{ github.event.pull_request.merged_by.login }}
          
          # Enforce rules for 'develop' and 'master'
          if [[ "$BRANCH" == "develop" || "$BRANCH" == "master" ]]; then
            if [[ "${{ github.event.pull_request.merge_commit_sha }}" == "" ]]; then
              echo "Error: Only merge commits are allowed for $BRANCH."
              exit 1
            fi
          fi

          # Enforce rules for feature branches
          if [[ "$BRANCH" =~ ^feature/ ]]; then
            if [[ "${{ github.event.pull_request.merge_commit_sha }}" != "" ]]; then
              echo "Error: Only squash merges are allowed for feature branches."
              exit 1
            fi
          fi
