name: Cleanup Stale Branches

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  pull-requests: read

jobs:
  cleanup-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Stale Branches
        uses: cbrgm/cleanup-stale-branches-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          last-commit-age-days: 90
          dry-run: true
